### ISSUE TITLE
Camera object has no attribute GVSPAdjustPacketSize in v0.3.2

### ISSUE THREAD

**Issue by PereeT** [morefigs/pymba#85]
First of all thank you for your work, I use Pymba for another camera and it works great.
I tried to use it for my new camera Mako U-130-B (USB3.0) and i got the message "Camera object has no attribute GVSPAdjustPacketSize" 
I checked the previous post and I saw that you tried to fix the problem with the version 0.3.2 but I'm using this version and I still got the issue. 
For now it isn't really a problem because I can still avoiding it by writing "camera_NIR.open(adjust_packet_size=False". But this solution is not perfect because I can't change the exposure time or the pixel format ("VimbaException: Operation is invalid with the current access mode"). However I can still change it manually with Vimba viewer.
I just wanted you to know that the issue is still present.
Best regards.

**Comment by morefigs** [comment]
Is the other camera an Ethernet camera? It looks like this bug is because `GVSPAdjustPacketSize` is called if you have the Ethernet transport layer present, even if that camera is not an Ethernet camera. I'll fix that soon.

In the meantime keep using `adjust_packet_size=False`. That should _not_ affect exposure time or pixel format, which sounds like an unrelated issue. Let me know if that continues.

**Comment by PereeT** [comment]
Yes it is! 
Thank you I'll continue to investigate in this case.

**Comment by morefigs** [comment]
Fixed in 0.3.3.
